' skinparam dpi 300
skinparam shadowing true
skinparam RoundCorner 8

skinparam Note {
    FontName STKaiTi
    ' FontSize 12
    BackgroundColor #FFDE61
    BorderColor #886F11
}
skinparam Arrow {
    Color #F91F02
    Thickness 1
    FontName STKaiTi
    ' FontSize 12
}

skinparam class {
    BackgroundColor #4C83FF/#ABDCFF
    BorderColor white
    FontName SimHei
    AttributeFontName STXinWei
}
skinparam stereotypeCBackgroundColor YellowGreen

skinparam Package {
    FontName STKaiTi
    ' FontSize 12
    BorderColor black
}